# Configuration Laravel Cloud minimale
# Évite tous les problèmes de build

[phases.setup]
  nixPkgs = [
    "php82Extensions.intl"
  ]

[phases.install]
  cmds = [
    "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader"
  ]

[phases.build]
  env = [
    "NIXPACKS_BUILD=true",
    "BUILD_PHASE=true"
  ]
  cmds = [
    "php artisan key:generate --force || true"
  ]

[start]
  cmd = "php -d variables_order=EGPCS -S 0.0.0.0:$PORT -t public public/index.php"
