[phases.setup]
  nixPkgs = [
    "php82Extensions.intl",
    "php82Extensions.zip",
    "php82Extensions.pdo_pgsql",
    "php82Extensions.pgsql",
    "php82Extensions.pdo_mysql",
    "php82Extensions.mysql"
  ]

[phases.install]
  cmds = [
    "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader"
  ]

[phases.build]
  cmds = [
    "php artisan key:generate --force || true",
    "php artisan config:clear || true",
    "php artisan route:clear || true",
    "php artisan view:clear || true",
    "php artisan laravel-cloud:fix-deployment || true",
    "php artisan fix:sessions-conflict || true",
    "php artisan migrate --force || true",
    "php artisan storage:link || true"
  ]

[start]
  cmd = "php -d variables_order=EGPCS -S 0.0.0.0:$PORT -t public public/index.php"


