[phases.setup]
  nixPkgs = [
    "php82Extensions.intl",
    "php82Extensions.zip"
  ]

[phases.install]
  cmds = [
    "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader"
  ]

[phases.build]
  env = [
    "NIXPACKS_BUILD=true",
    "BUILD_PHASE=true"
  ]
  cmds = [
    "php artisan key:generate --force || true",
    "php artisan config:clear || true",
    "php artisan route:clear || true",
    "php artisan view:clear || true",
    "php artisan fix:mysql-deadlocks || true",
    "php artisan storage:link || true"
  ]

[start]
  cmd = "php -d variables_order=EGPCS -S 0.0.0.0:$PORT -t public public/index.php"


