services:
  - type: web
    name: egliox-web
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: FILESYSTEM_DISK
        value: public
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_URL
        fromService:
          name: egliox-web
          type: web
          property: url
      - key: DATABASE_URL
        fromDatabase:
          name: egliox-db
          property: connectionString
      - key: DB_RESET_ON_DEPLOY
        value: false
    disk:
      name: storage
      mountPath: /app/storage
      sizeGB: 1
    buildCommand: |
      # Build handled by Dockerfile
      echo "Using Dockerfile build"
    startCommand: |
      # Start handled by Dockerfile CMD
      echo "Starting via Docker CMD"

databases:
  - name: egliox-db
    plan: free
